export const GOVERNOR_HOLDOVERS: Record<string, "Democratic" | "Republican"> = {
  Delaware: "Democratic",
  Kentucky: "Democratic",
  "North Carolina": "Democratic",
  "New Jersey": "Democratic",
  Washington: "Democratic",
  Virginia: "Democratic",
  Indiana: "Republican",
  Louisiana: "Republican",
  Mississippi: "Republican",
  Missouri: "Republican",
  Montana: "Republican",
  "North Dakota": "Republican",
  Utah: "Republican",
  "West Virginia": "Republican",
};

export const SENATE_HOLDOVERS: Record<string, ("Democratic" | "Republican")[]> =
  {
    // 15 States with no Senate races in 2026 (2 holdover seats each)
    Arizona: ["Democratic", "Democratic"],
    California: ["Democratic", "Democratic"],
    Connecticut: ["Democratic", "Democratic"],
    Hawaii: ["Democratic", "Democratic"],
    Indiana: ["Republican", "Republican"],
    Maryland: ["Democratic", "Democratic"],
    Missouri: ["Republican", "Republican"],
    Nevada: ["Democratic", "Democratic"],
    "New York": ["Democratic", "Democratic"],
    "North Dakota": ["Republican", "Republican"],
    Pennsylvania: ["Democratic", "Republican"],
    Utah: ["Republican", "Republican"],
    Vermont: ["Democratic", "Democratic"],
    Washington: ["Democratic", "Democratic"],
    Wisconsin: ["Democratic", "Republican"],

    // 2 States where both senators share the same party; race is in 2026 but listed here
    // so the non-contested holdover seat is counted when the race is active (1 seat counted),
    // or both seats are counted if no forecast exists (2 seats counted as baseline fallback).
    Virginia: ["Democratic", "Democratic"],
    "West Virginia": ["Republican", "Republican"],

    // 33 States with forecasted Senate races in 2026 (1 holdover seat each)
    Colorado: ["Democratic"],
    Delaware: ["Democratic"],
    Georgia: ["Democratic"],
    Illinois: ["Democratic"],
    Maine: ["Democratic"],
    Massachusetts: ["Democratic"],
    Michigan: ["Democratic"],
    Minnesota: ["Democratic"],
    "New Hampshire": ["Democratic"],
    "New Jersey": ["Democratic"],
    "New Mexico": ["Democratic"],
    Oregon: ["Democratic"],
    "Rhode Island": ["Democratic"],

    Alabama: ["Republican"],
    Alaska: ["Republican"],
    Arkansas: ["Republican"],
    Florida: ["Republican"],
    Idaho: ["Republican"],
    Iowa: ["Republican"],
    Kansas: ["Republican"],
    Kentucky: ["Republican"],
    Louisiana: ["Republican"],
    Mississippi: ["Republican"],
    Montana: ["Republican"],
    Nebraska: ["Republican"],
    "North Carolina": ["Republican"],
    Ohio: ["Republican"],
    Oklahoma: ["Republican"],
    "South Carolina": ["Republican"],
    "South Dakota": ["Republican"],
    Tennessee: ["Republican"],
    Texas: ["Republican"],
    Wyoming: ["Republican"],
  };
